"use client";

import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "fr" | "en";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // Navbar
    home: "Accueil",
    about: "À Propos",
    services: "Services",
    pages: "Pages",
    contact: "Contact",
    getStarted: "Commencer",
    Portfolio: "Portfolio",
    // Hero
    hero_title: "Distinguez-vous. Développez-vous. Bâtissez un moteur de revenus durable.",
    hero_subtext: "Fondé par un ancien spécialiste Google Ads",
    hero_desc: "Nous construisons des stratégies centrées sur l'utilisateur qui stimulent la conversion et le succès durable de votre marque.",
    hero_follow: "SUIVEZ-NOUS",
    hero_m1: ["Stratégie Créative", "Croissance Digitale", "Design UI/UX", "Réseaux Sociaux"],
    hero_m2: ["Google Ads", "Analyse de Marché", "Identité de Marque", "Expert SEO"],
    hero_m3: ["Solution Créative", "Moteur de Revenus", "Scalabilité", "Succès"],
    // Services Submenu
    service_web: "Développement Web",
    service_design: "Stratégie Design",
    service_seo: "Optimisation SEO",
    // Pages Submenu
    page_team: "Notre Équipe",
    page_careers: "Carrières",
    page_faq: "Support FAQ",
    // About
    about_bg: "À PROPOS",
    about_subtitle: "Founder & Former Google Ads Specialist",
    about_desc: "From Google HQ to Your Growth Engine.\nOur mission is to build strong digital foundations your business needs to grow sustainably. From paid advertising to brand strategy, we develop systems that ensure every dollar you invest helps you dominate your market.\n\n— Morene Niyomwungere, CEO & Founder",
    about_btn_learn: "En savoir plus",
    about_btn_work: "Voir comment ça marche",
    about_stat: "Évalué 4.9 Étoiles",
    // Services Section
    serv_bg: "NOS SERVICES",
    serv_subtitle: "Que faisons-nous ? Boostez votre marque avec M Consulting",
    serv_desc: "Nous fournissons des services de gestion des réseaux sociaux et de marketing digital pour aider votre entreprise à se démarquer et attirer le bon public.",
    serv_tag1: "Gestion Social Media",
    serv_tag2: "Création de Contenu",
    serv_tag3: "Influence & Collab",
    serv_tag4: "Publicités & Campagnes",
    serv_tag5: "Stratégie de Marque",
    serv_nav1: "Publication & Programmation",
    serv_nav2: "Engagement de l'audience",
    serv_nav3: "Recherche de Tendances",
    serv_nav4: "Analyses de Performance",
    // Showcase Section
    showcase_r1_1: "PROPULSER",
    showcase_r1_2: "VOTRE MARQUE*",
    showcase_r2_1: "SUR LA",
    showcase_r2_2: "BONNE PLATEFORME",
    showcase_r3_1: "-AU",
    showcase_r3_2: "BON MOMENT",
    showcase_r4_1: "AVEC UN",
    showcase_r4_2: "PLAN ASTUCIEUX.”",
    // Portfolio Section
    port_bg: "PORTFOLIO",
    port_title: "Histoires de Succès qui Inspirent la Croissance",
    port_desc: "Découvrez comment nos stratégies de marketing digital ont généré des résultats réels pour les marques du monde entier.",
    port_tag1: "Gestion Social Media",
    port_tag2: "Création de Contenu",
    port_tag3: "Direction Créative",
    port_tag4: "Ads & Campagnes",
    port_tag5: "Stratégie de Marque",
    project1_title: "Vision Tech Solutions",
    project1_cat: "Analyses de Performance",
    project1_desc: "Transformer les analyses en un moteur de marque puissant.",
    project2_title: "Identité Globale",
    project2_cat: "Direction Créative",
    project2_desc: "Élever l'identité globale par un design minimaliste.",
    project3_title: "Système ID Moderne",
    project3_cat: "Stratégie Visuelle",
    project3_desc: "Bâtir des systèmes ID intelligents pour les entreprises modernes.",
    project4_title: "Packaging Premium",
    project4_cat: "Branding Produit",
    project4_desc: "Packaging premium qui capture instantanément l'attention.",
    project5_title: "Engagement Social",
    project5_cat: "Stratégie de Contenu",
    project5_desc: "Contenu social stratégique qui génère un engagement réel.",
    // Why Choose Us Section
    choose_bg: "POURQUOI NOUS ?",
    choose_title: "Pourquoi nous choisir ? Le bon partenaire pour votre croissance",
    choose_desc: "Nous sommes plus qu'un simple service—nous sommes votre partenaire de croissance. Grâce à notre expertise et nos stratégies sur mesure, nous vous aidons à dominer votre marché.",
    choose_met1: "Stratégies d'Experts",
    choose_met2: "Contenu Engageant",
    choose_met3: "Résultats Prouvés",
    choose_met4: "Support Dédié",
    choose_stat1_label: "Projets Complétés",
    choose_stat2_label: "Années d'Expérience",
    choose_stat3_label: "Clients Satisfaits",
    // Solutions Section
    sol_bg: "NOS SOLUTIONS",
    sol_title: "Nos Solutions",
    sol_desc: "Des stratégies sur mesure pour transformer votre vision en résultats mesurables.",
    sol_c1_title: "Performance Marketing",
    sol_c1_desc: "Faites croître vos publicités avec des frameworks éprouvés.",
    sol_c1_f1: "Meta & TikTok Ads",
    sol_c1_f2: "Optimisation de Tunnel",
    sol_c1_f3: "A/B Testing Continu",
    sol_c1_f4: "Tracking Avancé",
    sol_c1_f5: "Scaling d'Audience",
    sol_c2_title: "Digital & Web",
    sol_c2_desc: "Transformez vos visiteurs en conversions réelles.",
    sol_c2_f1: "CRO (Optimisation Taux Conv.)",
    sol_c2_f2: "Stratégie UX/UI",
    sol_c2_f3: "Design Landing Page",
    sol_c2_f4: "Audit de Conversion",
    sol_c2_f5: "User Journey Mapping",
    sol_c3_title: "Brand Strategy",
    sol_c3_desc: "Bâtissez une marque qui capte l'attention durablement.",
    sol_c3_f1: "Positionnement de Marché",
    sol_c3_f2: "Identité Visuelle",
    sol_c3_f3: "Voix de la Marque",
    sol_c3_f4: "Roadmap Stratégique",
    sol_c3_f5: "Audit de Branding",
    sol_c4_title: "Strategic Training",
    sol_c4_desc: "Formation d'équipes pour une indépendance totale.",
    sol_c4_f1: "Workshops d'Équipe",
    sol_c4_f2: "Automatisation Process",
    sol_c4_f3: "SOP Documentation",
    sol_c4_f4: "Consulting Croissance",
    sol_c4_f5: "Mentoring Mensuel",
    // Form Labels
    form_title: "Nous Contacter",
    form_category: "Solution Sélectionnée",
    form_name: "Nom",
    form_surname: "Prénom",
    form_phone: "Numéro de téléphone",
    form_email: "Adresse Email",
    form_message: "Message",
    form_submit: "Envoyer le message",
    form_close: "Fermer",
    // Testimonials Section
    test_bg: "TÉMOIGNAGES",
    test_title1: "SUCCESS STORIES DE",
    test_title2: "NOS CLIENTS",
    test_desc: "De la stratégie à l'exécution, voici comment nous avons fait la différence pour nos clients.",
    test_c1_name: "SARAH LEMOINE",
    test_c1_role: "Directrice Générale, TechVision",
    test_c1_text: "La stratégie digitale mise en place par M Consulting a transformé notre présence en ligne. Notre taux de conversion a augmenté de 40% en seulement 3 mois.",
    test_c2_name: "MARC DUBOIS",
    test_c2_role: "Fondateur, GreenStep",
    test_c2_text: "Leur stratégie de marque ne nous a pas seulement donné un nouveau logo ; elle nous a donné une voix qui résonne avec notre public cible.",
    test_c3_name: "ELENA KOVIC",
    test_c3_role: "Directrice Marketing",
    test_c3_text: "Les résultats du marketing de performance ont dépassé nos attentes. Un ciblage précis et un ROI incroyable.",
    test_c4_name: "THOMAS ROUX",
    test_c4_role: "Entrepreneur",
    test_c4_text: "L'équipe a rendu tout si facile à comprendre. Maintenant, notre présence sociale est un véritable moteur de croissance.",
    // FAQ Section
    faq_bg: "QUESTIONS",
    faq_main: "Vos Questions, Nos Réponses",
    faq_q1: "Pourquoi choisir M Consulting ?",
    faq_a1: "Nous combinons créativité et stratégies basées sur les données pour assurer une croissance maximale. Notre équipe d'experts analyse les tendances et le comportement de votre audience.",
    faq_q2: "Faut-il signer un contrat long terme ?",
    faq_a2: "Non, nos offres sont flexibles. Nous croyons en la valeur que nous apportons plutôt qu'en des engagements contraignants.",
    faq_q3: "Quand verrai-je les premiers résultats ?",
    faq_a3: "Généralement, une amélioration de l'engagement se voit dès le premier mois, avec des conversions significatives sous 3 mois.",
    faq_q4: "Puis-je personnaliser un pack ?",
    faq_a4: "Absolument. Chaque entreprise est unique et nous adaptons nos solutions à vos objectifs spécifiques.",
    // CTA Section
    cta_ready: "PRÊT À BOOSTER VOTRE",
    cta_mid: "PRÉSENCE DIGITALE",
    cta_growth: "CROISSANCE",
    cta_desc: "Développez votre entreprise en ligne avec des stratégies marketing intelligentes. Propulsons votre marque au niveau supérieur !",
    cta_app: "Télécharger notre App",
    cta_start: "Commencer le Projet",
    // Footer Section
    foo_desc: "Transformer les marques en leaders digitaux grâce à l'innovation et à la stratégie.",
    foo_links: "Liens Utiles",
    foo_serv: "Services",
    foo_contact: "Contact",
    foo_copy: "© 2026 M Consulting. Tous droits réservés.",
    foo_loc: "Paris, France",
    foo_faq: "FAQ",
    // Pre-Footer Section
    prefoo_ready: "PRÊT À FAIRE GRANDIR VOTRE MARQUE ?",
    prefoo_tagline: "Faisons passer votre marque au niveau supérieur. Contactez-nous !",
    prefoo_slogan: "CRÉATIF. STRATÉGIQUE. PROFESSIONNEL.",
    // Contact Page
    con_hero_t1: "CONTACTEZ-NOUS",
    con_hero_t2: "TRANSFORMONS VOTRE PRÉSENCE",
    con_office_t: "Notre Siège",
    con_office_a: "Paris, France - 8e Arrondissement",
    con_support_t: "Support 24/7",
    con_support_d: "Nous sommes là pour répondre à vos questions.",
    con_form_t: "Démarrer un Projet",
    con_form_sub: "Racontez-nous vos objectifs et nous reviendrons vers vous sous 24h.",
    con_email_us: "Nous Écrire",
    con_call_us: "Nous Appeler",
    con_website: "Notre Site",
    con_subject: "Sujet",
    con_other: "Autre / Demande Générale"
  },
  en: {
    // Navbar
    home: "Home",
    about: "About",
    services: "Services",
    pages: "Pages",
    contact: "Contact",
    getStarted: "Get Started",
    Portfolio: "Portfolio",
    // Hero
    hero_title: "Stand Out. Scale Up. Build a Sustainable Revenue Engine.",
    hero_subtext: "Founded by a former Google Ads Specialist",
    hero_desc: "We build user-centric strategies that drive conversion and sustainable brand success.",
    hero_follow: "FOLLOW US",
    hero_m1: ["Creative Strategy", "Digital Growth", "UI/UX Design", "Social Media"],
    hero_m2: ["Google Ads", "Market Analysis", "Brand Identity", "SEO Expert"],
    hero_m3: ["Creative Solution", "Revenue Engine", "Scalability", "Success"],
    // Services Submenu
    service_web: "Web Development",
    service_design: "Design Strategy",
    service_seo: "SEO Optimization",
    // Pages Submenu
    page_team: "Our Team",
    page_careers: "Careers",
    page_faq: "FAQ Support",
    // About
    about_bg: "ABOUT US",
    about_subtitle: "Founder & Former Google Ads Specialist",
    about_desc: "From Google HQ to Your Growth Engine.\nOur mission is to build strong digital foundations your business needs to grow sustainably. From paid advertising to brand strategy, we develop systems that ensure every dollar you invest helps you dominate your market.\n\n— Morene Niyomwungere, CEO & Founder",
    about_btn_learn: "Learn More",
    about_btn_work: "See How It Work",
    about_stat: "4.9 Star Reviewer",
    // Services Section
    serv_bg: "OUR SERVICES",
    serv_subtitle: "What We Do? Boost Your Brand with M Consulting",
    serv_desc: "We provide social media and digital marketing services to help your business stand out, attract the right audience.",
    serv_tag1: "Social Media Management",
    serv_tag2: "Content Creation",
    serv_tag3: "Influencer & Brand Collab",
    serv_tag4: "Paid Ads & Campaign",
    serv_tag5: "Brand Strategy & Growth",
    serv_nav1: "Content Posting & Scheduling",
    serv_nav2: "Audience Engagement",
    serv_nav3: "Hashtag & Trend Research",
    serv_nav4: "Performance Analytics",
    // Showcase Section
    showcase_r1_1: "GROWING",
    showcase_r1_2: "YOUR BRAND*",
    showcase_r2_1: "ON THE",
    showcase_r2_2: "RIGHT PLATFORM",
    showcase_r3_1: "-AT",
    showcase_r3_2: "THE RIGHT TIME",
    showcase_r4_1: "WITH A",
    showcase_r4_2: "SMART PLAN.”",
    // Portfolio Section
    port_bg: "PORTFOLIO",
    port_title: "Success Stories That Inspire Growth",
    port_desc: "Discover how our digital marketing strategies have driven real results for brands worldwide.",
    port_tag1: "Social Media Management",
    port_tag2: "Content Creation",
    port_tag3: "Creative Direction",
    port_tag4: "Paid Ads & Campaigns",
    port_tag5: "Brand Strategy & Growth",
    project1_title: "Vision Tech Solutions",
    project1_cat: "Performance Analytics",
    project1_desc: "Transforming analytics into a powerful brand engine.",
    project2_title: "Global Brand Identity",
    project2_cat: "Creative Direction",
    project2_desc: "Elevating global identity through minimalist design.",
    project3_title: "Modern ID System",
    project3_cat: "Visual Strategy",
    project3_desc: "Building smart ID systems for modern businesses.",
    project4_title: "Premium Packaging",
    project4_cat: "Product Branding",
    project4_desc: "Premium packaging that captures attention instantly.",
    project5_title: "Social Engagement",
    project5_cat: "Content Strategy",
    project5_desc: "Strategic social content that drives real engagement.",
    // Why Choose Us Section
    choose_bg: "WHY CHOOSE US",
    choose_title: "Why Choose Us? The Right Partner for Your Growth",
    choose_desc: "We’re more than just a service—we’re your growth partner. With our expertise and tailored strategies, we help you dominate your market.",
    choose_met1: "Expert Strategies",
    choose_met2: "Engaging Content",
    choose_met3: "Proven Results",
    choose_met4: "Dedicated Support",
    choose_stat1_label: "Completed Projects",
    choose_stat2_label: "Years Experience",
    choose_stat3_label: "Satisfied Clients",
    // Solutions Section
    sol_bg: "OUR SOLUTIONS",
    sol_title: "Our Solutions",
    sol_desc: "Tailored strategies designed to turn your vision into measurable results.",
    sol_c1_title: "Performance Marketing",
    sol_c1_desc: "Scaling ads with proven frameworks.",
    sol_c1_f1: "Meta & TikTok Ads",
    sol_c1_f2: "Funnel Optimization",
    sol_c1_f3: "Continuous A/B Testing",
    sol_c1_f4: "Advanced Tracking",
    sol_c1_f5: "Audience Scaling",
    sol_c2_title: "Digital & Web",
    sol_c2_desc: "Turn website visitors into conversions.",
    sol_c2_f1: "CRO (Conversion Optimization)",
    sol_c2_f2: "UX/UI Strategy",
    sol_c2_f3: "Landing Page Design",
    sol_c2_f4: "Conversion Audit",
    sol_c2_f5: "User Journey Mapping",
    sol_c3_title: "Brand Strategy",
    sol_c3_desc: "Position and build a brand that commands attention.",
    sol_c3_f1: "Market Positioning",
    sol_c3_f2: "Visual Identity",
    sol_c3_f3: "Brand Voice & Tone",
    sol_c3_f4: "Strategic Roadmap",
    sol_c3_f5: "Branding Audit",
    sol_c4_title: "Strategic Training",
    sol_c4_desc: "Training teams to maintain growth and independence.",
    sol_c4_f1: "Team Workshops",
    sol_c4_f2: "Process Automation",
    sol_c4_f3: "SOP Documentation",
    sol_c4_f4: "Growth Consulting",
    sol_c4_f5: "Monthly Mentoring",
    // Form Labels
    form_title: "Get in Touch",
    form_category: "Selected Solution",
    form_name: "Last Name",
    form_surname: "First Name",
    form_phone: "Phone Number",
    form_email: "Email Address",
    form_message: "Your Message",
    form_submit: "Send Message",
    form_close: "Close",
    // Testimonials Section
    test_bg: "TESTIMONIALS",
    test_title1: "SUCCESS STORIES FROM",
    test_title2: "OUR CLIENTS",
    test_desc: "From strategy to execution, here's how we've made a difference for our clients.",
    test_c1_name: "SARAH LEMOINE",
    test_c1_role: "CEO, TechVision",
    test_c1_text: "The digital strategy implemented by M Consulting transformed our online presence. Our conversion rate increased by 40% in just 3 months.",
    test_c2_name: "MARC DUBOIS",
    test_c2_role: "Founder, GreenStep",
    test_c2_text: "Their brand strategy didn't just give us a new logo; it gave us a voice that resonates with our target audience.",
    test_c3_name: "ELENA KOVIC",
    test_c3_role: "Marketing Director",
    test_c3_text: "The performance marketing results were beyond our expectations. Precise targeting and incredible ROI.",
    test_c4_name: "THOMAS ROUX",
    test_c4_role: "Entrepreneur",
    test_c4_text: "The team made everything so easy to understand. Now, our social presence is a real engine for growth.",
    // FAQ Section
    faq_bg: "QUESTIONS",
    faq_main: "Your Questions, Answered",
    faq_q1: "Why choose M Consulting?",
    faq_a1: "We combine creativity with data-driven strategies for maximum growth. Our team of experts analyzes trends and audience behavior.",
    faq_q2: "Do I need a long-term contract?",
    faq_a2: "No, our plans are flexible. We believe in the value we deliver rather than long-term lock-ins.",
    faq_q3: "How soon can I see results?",
    faq_a3: "Usually, engagement improvements are seen within the first month, with significant conversions within 3 months.",
    faq_q4: "Can I customize a package?",
    faq_a4: "Absolutely. Every business is unique and we tailor our solutions to your specific goals.",
    // CTA Section
    cta_ready: "READY TO BOOST YOUR",
    cta_mid: "DIGITAL PRESENCE",
    cta_growth: "GROWTH",
    cta_desc: "Grow your business online with smart marketing strategies. Let’s take your brand to the next level!",
    cta_app: "Download Our App",
    cta_start: "Start Your Project",
    // Footer Section
    foo_desc: "Transforming brands into digital leaders through innovation and strategy.",
    foo_links: "Useful Links",
    foo_serv: "Services",
    foo_contact: "Contact",
    foo_copy: "© 2026 M Consulting. All rights reserved.",
    foo_loc: "Paris, France",
    foo_faq: "FAQ",
    // Pre-Footer Section
    prefoo_ready: "READY TO GROW YOUR BRAND?",
    prefoo_tagline: "Let’s take your brand to the next level. Get in touch!",
    prefoo_slogan: "CREATIVE. STRATEGIC. PROFESSIONAL.",
    // Contact Page
    con_hero_t1: "CONTACT US",
    con_hero_t2: "TRANSFORM YOUR PRESENCE",
    con_office_t: "Our Headquarters",
    con_office_a: "Paris, France - 8th District",
    con_support_t: "24/7 Support",
    con_support_d: "We're here to answer your questions anytime.",
    con_form_t: "Start a Project",
    con_form_sub: "Tell us about your goals and we'll get back to you within 24h.",
    con_email_us: "Email Us",
    con_call_us: "Call Us",
    con_website: "Our Website",
    con_subject: "Subject",
    con_other: "Other / General Inquiry"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>("fr");

  const t = (key: string) => {
    return (translations[lang] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
